spring:
  active:
    profiles: local
---
spring:
  profiles: local
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka
